### PR TITLE
FE-6454

### PR DESCRIPTION
**Pull request by EricTRocks**
@reality3d @pzion A separate sub-process is required in order to set the PATH variable and have it take affect when launching canvas.py

changes: Added a new canvas_launcher.py file to launch canvas.py simply by double clicking the canvas_launcher.py file.

test: Yes works well.

risk: very low.

### CODE REVIEW

**Comment by pzion** [comment]
This is definitely better than before, but it's unfortunate that we have to maintain the environment variables in yet another place.  I think this is OK for now but we really need to think about how we could have a single place where all the variables are set so we don't forget a place when we need to add or modify a variable.

**Comment by ktureski** [comment]
What documentation needs to change as a result of this? And was it updated?

**Comment by EricTRocks** [comment]
I don't particularly like this solution. Instead what I've always done is create a `canvas.bat` file with the following contents and put it in the root Fabric folder:

```
call environment.bat

call python bin/canvas.py
```

**Benefits to the above approach:**
- Requires only 1 new 3 line file
- This can be launched by double clicking
- Users can make shortcuts to it 
- You can change the icon of the shortcut to the Fabric icon via the canvas.exe

**Comment by EricTRocks** [comment]
We're going with the canvas.bat / .sh option. Closing this as the work will be done on the SceneGraph repo

**Pull request closed without merging**
