### PR TITLE
Set text color on ScriptEditor buttons to fix on OSX

### PR DESCRIPTION
**Pull request by EricTRocks**

### CODE REVIEW

**Comment by EricTRocks** [comment]
@reality3d this Fixes FE-6594. Please review on OSX and confirm it's fixed.

**Comment by andrewmacp** [comment]
This will help with the merging:

http://confluence.fabricengine.com:8090/display/ENG/Merging+in+changes+from+subtree+repos

**Comment by reality3d** [comment]
Works fine! :)

**Comment by reality3d** [comment]
And thanks for the doc @andrewmacp !

**Pull request merged**
